blank_issues_enabled: false
contact_links:
  - name: 💬 GitHub Discussions
    url: https://github.com/dmautz1/ai-agent-platform/discussions
    about: Ask questions, share ideas, and discuss with the community
  - name: 📖 Documentation
    url: https://github.com/dmautz1/ai-agent-platform/blob/main/README.md
    about: Check our comprehensive documentation for setup and usage guides
  - name: 🔒 Security Issues
    url: https://github.com/dmautz1/ai-agent-platform/security/advisories/new
    about: Report security vulnerabilities privately through GitHub Security Advisories
  - name: 🚀 Quick Start Guide
    url: https://github.com/dmautz1/ai-agent-platform/blob/main/docs/getting-started/quick-start.md
    about: Get started with AI Agent Platform in 30 minutes 